# Generated by Django 4.1.1 on 2022-10-01 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_statistics', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='statistics',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_statistics.userstatistics'),
        ),
    ]
