# Generated by Django 4.1.1 on 2022-10-01 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_statistics', '0001_initial'),
        ('users', '0002_customuser_statistics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='statistics',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_statistics.userstatistics'),
        ),
    ]
