# Generated by Django 4.1.1 on 2022-10-01 12:08

import ctimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CTImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('healthy', 'Healthy'), ('pneumoniaB', 'Pneumonia Bacterial'), ('pneumoniaV', 'Pneumonia Viral'), ('tuberculosis', 'Tuberculosis'), ('covid', 'Covid'), ('edema', 'Edema'), ('lesion', 'Lung Lesion')], max_length=100, unique=True)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to=ctimage.models.upload_to)),
            ],
        ),
    ]
