# Generated by Django 4.1.1 on 2022-10-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctimage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctimage',
            name='category',
            field=models.CharField(choices=[('healthy', 'Healthy'), ('pneumoniaB', 'Pneumonia Bacterial'), ('pneumoniaV', 'Pneumonia Viral'), ('tuberculosis', 'Tuberculosis'), ('covid', 'Covid'), ('edema', 'Edema'), ('lesion', 'Lung Lesion')], max_length=100),
        ),
    ]
