# Generated by Django 4.1.1 on 2022-11-19 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_statistics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userstatistics',
            old_name='covid_correct_count',
            new_name='issues_solved',
        ),
        migrations.RemoveField(
            model_name='userstatistics',
            name='covid_count',
        ),
        migrations.RemoveField(
            model_name='userstatistics',
            name='healthy_correct_count',
        ),
        migrations.RemoveField(
            model_name='userstatistics',
            name='healthy_count',
        ),
        migrations.RemoveField(
            model_name='userstatistics',
            name='pneunomia_correct_count',
        ),
        migrations.RemoveField(
            model_name='userstatistics',
            name='pneunomia_count',
        ),
        migrations.RemoveField(
            model_name='userstatistics',
            name='total_correct_count',
        ),
        migrations.RemoveField(
            model_name='userstatistics',
            name='total_count',
        ),
        migrations.RemoveField(
            model_name='userstatistics',
            name='tuberculosis_correct_count',
        ),
        migrations.RemoveField(
            model_name='userstatistics',
            name='tuberculosis_count',
        ),
    ]
